# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Install 🔧
        run: npm install

      - name: Run Test 🔨
        run: npm run test

      - name: Build 👷
        run: npm run build

      - name: Deploy 🚀
        uses: Vampirus555/Dictionary@0.0.0
        with:
          # в значение GITHUB_TOKEN помещается ссылка на ваш секрет в репозитории
          # в данном случае его название KEY
          GITHUB_TOKEN: ${{ secrets.KEY }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
